Release workflow - change release numbering

diff --git a/.github/workflows/release-workflow.yaml b/.github/workflows/release-workflow.yaml
--- a/.github/workflows/release-workflow.yaml
+++ b/.github/workflows/release-workflow.yaml
@@ -32,7 +32,13 @@ jobs:
       run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
 
     - name: Update version in pyproject.toml
-      run: sed -i "s/version = \".*\"/version = \"$RELEASE_VERSION\"/" pyproject.toml
+      run: |
+        if [[ $RELEASE_VERSION =~ ^v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
+          poetry version ${BASH_REMATCH[1]}
+        else
+          echo "Invalid release tag format: $RELEASE_VERSION"
+          exit 1
+        fi
 
     - name: Build package
       run: poetry build
